apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dream-journal
  labels:
    app.kubernetes.io/name: dream-journal
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: dream-journal
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dream-journal
        app.kubernetes.io/component: backend
    spec:
      serviceAccountName: dream-journal-app
      initContainers:
      # Run migrations before starting the main container
      - name: django-migrate
        image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/dream-journal/backend:${SHORT_SHA}
        command: ["/usr/bin/python3.11", "manage.py", "migrate", "--noinput"]
        env:
        - name: PYTHONPATH
          value: "/app:/home/venv/lib/python3.11/site-packages"
        - name: DEBUG
          value: "False"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: secret-key
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: database-url
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: sendgrid-api-key
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 65531  # Different user for migration container
          capabilities:
            drop:
            - ALL
      # Create admin user after migrations
      - name: django-create-admin
        image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/dream-journal/backend:${SHORT_SHA}
        command: ["/usr/bin/python3.11", "manage.py", "create_admin"]
        env:
        - name: PYTHONPATH
          value: "/app:/home/venv/lib/python3.11/site-packages"
        - name: DEBUG
          value: "False"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: secret-key
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: database-url
        - name: DJANGO_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: django-admin-password
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 65533  # Different user for admin creation container
          capabilities:
            drop:
            - ALL
      containers:
      - name: backend
        image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/dream-journal/backend:${SHORT_SHA}
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "False"
        - name: ALLOWED_HOSTS
          value: "sensorium.dev,admin.sensorium.dev,localhost,127.0.0.1"
        - name: ALLOWED_CIDR_NETS
          value: "10.1.0.0/16"
        - name: CORS_ALLOWED_ORIGINS
          value: "https://sensorium.dev"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: secret-key
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: database-url
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: sendgrid-api-key
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 65532
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
