apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  namespace: dream-journal
  labels:
    app.kubernetes.io/name: dream-journal
    app.kubernetes.io/component: migration
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dream-journal
        app.kubernetes.io/component: migration
    spec:
      serviceAccountName: dream-journal-app
      restartPolicy: Never
      containers:
      - name: migrate
        image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/dream-journal/backend:latest
        command: ["/usr/bin/python3.11", "manage.py", "migrate"]
        env:
        - name: PYTHONPATH
          value: "/app:/home/venv/lib/python3.11/site-packages"
        - name: DEBUG
          value: "False"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: secret-key
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: database-url
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 65532
          capabilities:
            drop:
            - ALL
  backoffLimit: 3