apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dream-journal-frontend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      serviceAccountName: cloud-run-app@${PROJECT_ID}.iam.gserviceaccount.com
      containers:
      - image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/dream-journal/frontend:${SHORT_SHA}
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 30
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true
