# Cloud Build configuration for Dream Journal Backend and Celery Worker
# Deploys both services to Cloud Run using service configuration YAML

steps:
  # Build the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/backend:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/backend:latest'
      - '.'
    dir: 'backend'
    id: 'build-backend'

  # Build the worker Docker image (parallel with backend)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.worker'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/celery-worker:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/celery-worker:latest'
      - '.'
    dir: 'backend'
    id: 'build-worker'

  # Push the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/backend'
    id: 'push-backend'
    waitFor: ['build-backend']

  # Push the worker Docker image (parallel with backend push)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/celery-worker'
    id: 'push-worker'
    waitFor: ['build-worker']

  # Run database migrations
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Set environment variables for envsubst
        export PROJECT_ID=${_PROJECT_ID}
        export REGION=${_REGION}
        export SHORT_SHA=${SHORT_SHA}

        # Install envsubst for variable substitution
        apt-get update && apt-get install -y gettext-base

        # Process and execute migration job
        echo "Processing backend/migration-job.yaml"
        envsubst < "backend/migration-job.yaml" > /tmp/processed-migration-job.yaml
        gcloud run jobs replace /tmp/processed-migration-job.yaml --region=${_REGION}

        # Execute the migration job
        echo "Running database migrations"
        gcloud run jobs execute dream-journal-migrations --region=${_REGION} --wait
    id: 'run-migrations'
    waitFor: ['push-backend']

  # Deploy Cloud Run service
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Set environment variables for envsubst
        export PROJECT_ID=${_PROJECT_ID}
        export REGION=${_REGION}
        export SHORT_SHA=${SHORT_SHA}

        # Install envsubst for variable substitution
        apt-get update && apt-get install -y gettext-base

        # Process and deploy service configuration
        echo "Processing backend/cloud-run-service.yaml"
        envsubst < "backend/cloud-run-service.yaml" > /tmp/processed-service.yaml
        gcloud run services replace /tmp/processed-service.yaml --region=${_REGION}

        # Note: Public access will be configured via domain mapping in Terraform
    id: 'deploy-service'
    waitFor: ['run-migrations']

  # Deploy Cloud Run worker pool for Celery workers
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Deploy Celery workers to Cloud Run worker pool
        echo "Deploying Celery workers to Cloud Run worker pool"

        gcloud beta run worker-pools deploy dream-journal-celery-worker-pool \
          --image=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/celery-worker:${SHORT_SHA} \
          --region=${_REGION} \
          --cpu=1 \
          --memory=512Mi \
          --service-account=cloud-run-app@${_PROJECT_ID}.iam.gserviceaccount.com \
          --set-env-vars=DJANGO_SETTINGS_MODULE=dream_journal.settings,DEBUG=False,GCS_BUCKET_NAME=${_PROJECT_ID}-dream-images,GOOGLE_CLOUD_PROJECT=${_PROJECT_ID} \
          --set-secrets=DATABASE_URL=database-url:latest,GEMINI_API_KEY=gemini-api-key:latest,SECRET_KEY=django-secret-key:latest \
          --set-cloudsql-instances=${_PROJECT_ID}:${_REGION}:dream-journal-postgres \
          --network=dream-journal-vpc \
          --subnet=dream-journal-subnet \
          --vpc-egress=all-traffic
    id: 'deploy-worker'
    waitFor: ['push-worker']

# Substitutions (configure sensitive values in Cloud Build trigger)
substitutions:
  # _PROJECT_ID: Set this in Cloud Build trigger substitutions
  _REGION: 'us-central1'
  _REPOSITORY: 'dream-journal'

# Build options
options:
  machineType: 'E2_MEDIUM'
  substitution_option: 'ALLOW_LOOSE'
  logging: 'CLOUD_LOGGING_ONLY'

# Build timeout
timeout: '1200s'

# Images to be pushed to registry
images:
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/backend:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/backend:latest'
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/celery-worker:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/celery-worker:latest'
