apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dream-journal-celery-worker
  annotations:
    run.googleapis.com/ingress: internal
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/vpc-access-connector: dream-journal-connector
        run.googleapis.com/vpc-access-egress: all-traffic
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      serviceAccountName: celery-worker@${PROJECT_ID}.iam.gserviceaccount.com
      containers:
      - image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/dream-journal/celery-worker:${SHORT_SHA}
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "dream_journal.settings"
        - name: DEBUG
          value: "False"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-url
              key: latest
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-api-key
              key: latest
        - name: GCS_BUCKET_NAME
          value: "${PROJECT_ID}-dream-images"
        - name: GOOGLE_CLOUD_PROJECT
          value: "${PROJECT_ID}"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret-key
              key: latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 60
          failureThreshold: 3
