# Cloud Build configuration for Dream Journal Backend
# Deploys to Cloud Run using service configuration YAML

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/backend:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/backend:latest'
      - './backend'
    id: 'build-backend'

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/backend'
    id: 'push-backend'
    waitFor: ['build-backend']

  # Run database migrations
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Set environment variables for envsubst
        export PROJECT_ID=${_PROJECT_ID}
        export REGION=${_REGION}
        export SHORT_SHA=${SHORT_SHA}

        # Install envsubst for variable substitution
        apt-get update && apt-get install -y gettext-base

        # Process and execute migration job
        echo "Processing backend/migration-job.yaml"
        envsubst < "backend/migration-job.yaml" > /tmp/processed-migration-job.yaml
        gcloud run jobs replace /tmp/processed-migration-job.yaml --region=${_REGION}

        # Execute the migration job
        echo "Running database migrations"
        gcloud run jobs execute dream-journal-migrations --region=${_REGION} --wait
    id: 'run-migrations'
    waitFor: ['push-backend']

  # Deploy Cloud Run service
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Set environment variables for envsubst
        export PROJECT_ID=${_PROJECT_ID}
        export REGION=${_REGION}
        export SHORT_SHA=${SHORT_SHA}

        # Install envsubst for variable substitution
        apt-get update && apt-get install -y gettext-base

        # Process and deploy service configuration
        echo "Processing backend/cloud-run-service.yaml"
        envsubst < "backend/cloud-run-service.yaml" > /tmp/processed-service.yaml
        gcloud run services replace /tmp/processed-service.yaml --region=${_REGION}

        # Note: Public access will be configured via domain mapping in Terraform
    id: 'deploy-service'
    waitFor: ['run-migrations']

# Substitutions (configure sensitive values in Cloud Build trigger)
substitutions:
  # _PROJECT_ID: Set this in Cloud Build trigger substitutions
  _REGION: 'us-central1'
  _REPOSITORY: 'dream-journal'

# Build options
options:
  machineType: 'E2_MEDIUM'
  substitution_option: 'ALLOW_LOOSE'
  logging: 'CLOUD_LOGGING_ONLY'

# Build timeout
timeout: '1200s'

# Images to be pushed to registry
images:
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/backend:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/backend:latest'
