apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: dream-journal-migrations
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/vpc-access-connector: dream-journal-connector
        run.googleapis.com/vpc-access-egress: private-ranges-only
    spec:
      taskCount: 1
      maxRetries: 3
      parallelism: 1
      template:
        spec:
          serviceAccountName: cloud-run-app@${PROJECT_ID}.iam.gserviceaccount.com
          timeoutSeconds: 600
          containers:
          - image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/dream-journal/backend:${SHORT_SHA}
            command: ["/usr/bin/python3.11", "manage.py", "migrate", "--noinput"]
            env:
            - name: PYTHONPATH
              value: "/app:/home/venv/lib/python3.11/site-packages"
            - name: DEBUG
              value: "False"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret-key
                  key: latest
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-url
                  key: latest
            resources:
              limits:
                memory: "512Mi"
                cpu: "1000m"
