[tool.ruff]
target-version = "py313"
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "I",    # isort
    "B",    # flake8-bugbear
    "UP",   # pyupgrade
    "DJ",   # flake8-django
    "ANN",  # flake8-annotations (type hints)
    "TCH",  # flake8-type-checking
    "TID",  # flake8-tidy-imports
    "RUF",  # Ruff-specific rules
]
ignore = [
    "E501",     # Line too long (handled by formatter)
    "ANN101",   # Missing type annotation for self in method
    "ANN102",   # Missing type annotation for cls in classmethod
]

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = false
suppress-dummy-args = false
suppress-none-returning = false
mypy-init-return = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

[tool.ruff.lint.isort]
known-third-party = ["django", "rest_framework"]

[tool.ruff.lint.per-file-ignores]
"*/migrations/*" = ["E501", "ANN"]
"*/settings/*" = ["F403", "F405", "ANN"]
"*/tests/*" = ["ANN201"]  # Allow missing return type annotations in tests
"manage.py" = ["ANN"]
"*/urls.py" = ["ANN001"]  # Allow missing variable annotations in URL configs