# Generated by Django 5.2.5 on 2025-08-23 16:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A 128 character quality descriptor",
                        max_length=128,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "frequency",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of dreams this quality appears in"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this quality",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Qualities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Dream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the dream"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the dream entry was first created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the dream entry was last modified",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this dream entry",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qualities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Single-word qualities describing this dream",
                        to="dreams.quality",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.AddIndex(
            model_name="quality",
            index=models.Index(
                fields=["user", "name"], name="dreams_qual_user_id_913fad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quality",
            index=models.Index(
                fields=["user", "-frequency"], name="dreams_qual_user_id_dc7de6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quality",
            unique_together={("user", "name")},
        ),
        migrations.AddIndex(
            model_name="dream",
            index=models.Index(
                fields=["user", "-created"], name="dreams_drea_user_id_10ca8c_idx"
            ),
        ),
    ]
