# Generated by Django 5.2.5 on 2025-08-24 22:54

from django.db import migrations


def update_site_domain(apps, schema_editor):
    """Update the default Site to use sensorium.dev domain"""
    Site = apps.get_model("sites", "Site")
    try:
        site = Site.objects.get(id=1)
        site.domain = "sensorium.dev"
        site.name = "Dream Journal"
        site.save()
    except Site.DoesNotExist:
        # Create the site if it doesn't exist
        Site.objects.create(id=1, domain="sensorium.dev", name="Dream Journal")


def reverse_site_domain(apps, schema_editor):
    """Reverse the site domain change"""
    Site = apps.get_model("sites", "Site")
    try:
        site = Site.objects.get(id=1)
        site.domain = "example.com"
        site.name = "example.com"
        site.save()
    except Site.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("dreams", "0001_initial"),
        ("sites", "0002_alter_domain_unique"),  # Ensure sites app is migrated
    ]

    operations = [
        migrations.RunPython(update_site_domain, reverse_site_domain),
    ]
