# Generated by Django 5.2.5 on 2025-08-30 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dreams", "0002_auto_20250824_2254"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gcs_path",
                    models.CharField(
                        help_text="Path to the image file in Google Cloud Storage",
                        max_length=512,
                    ),
                ),
                (
                    "generation_prompt",
                    models.TextField(
                        help_text="The prompt used to generate this image"
                    ),
                ),
                (
                    "generation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current status of image generation",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "dream",
                    models.ForeignKey(
                        help_text="The dream this image belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="dreams.dream",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["dream", "-created"],
                        name="dreams_imag_dream_i_cf8f16_idx",
                    ),
                    models.Index(
                        fields=["generation_status"],
                        name="dreams_imag_generat_571755_idx",
                    ),
                ],
            },
        ),
    ]
