# Generated by Django 5.2.5 on 2025-09-05 01:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dreams", "0003_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dream",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Whether this dream is shared anonymously in The Astral Plane",
            ),
        ),
        migrations.AddIndex(
            model_name="dream",
            index=models.Index(
                fields=["is_public", "-created"], name="dreams_drea_is_publ_02dd42_idx"
            ),
        ),
    ]
