apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dream-journal
  labels:
    app.kubernetes.io/name: dream-journal
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/name: dream-journal
    app.kubernetes.io/component: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP