services:
  postgres:
    image: postgres:16-alpine
    container_name: dreamjournal-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: dreamjournal
      POSTGRES_PASSWORD: dreamjournal
      POSTGRES_DB: dreamjournal
    ports:
      - "9002:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dreamjournal"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: dreamjournal-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "9003:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data:
